server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/travel
    username: travel
    password: travel

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

  cache:
    type: none

logging:
  level:
    org.springframework.boot.context.config: debug
    org.hibernate.tool.schema: debug

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui